#!/usr/bin/perl
use POSIX qw/floor/;
foreach my $rev (`git rev-list --all --pretty=oneline`) {
  my $tot = 0;
  ($sha = $rev) =~ s/\s.*$//;
  foreach my $blob (`git diff-tree -r -c -M -C --no-commit-id $sha`) {
    $blob = (split /\s/, $blob)[3];
    next if $blob == "0000000000000000000000000000000000000000"; # Deleted
    my $size = `echo $blob | git cat-file --batch-check`;
    $size = (split /\s/, $size)[2];
    $tot += int($size);
  }
  my $revn = substr($rev, 0, 40);
  if ($tot > 1000000) {
    my $finalsize = floor($tot/1000.0);
    print "size \t $finalsize Kb \t revision \t $revn \t file-count \t" . `git show --pretty="format:" --name-only $revn | wc -l`  ;
  } else {
    print "size \t $tot b \t revision \t $revn \t file-count \t" . `git show --pretty="format:" --name-only $revn | wc -l`  ;
  }
}
